### Data Structure

**Topics**

- Objects
- Vector
- Matrix
- DataFrame
- OOP
- Functions
- Loop statement
- Structure

#### 1. Objects

변수에 값을 초기화할 때에는 '='와 '<-' 둘 다 사용 가능하다

In [1]:
x = 10
x

[1] 10

In [2]:
y <- 100 
y

[1] 100

do not give blank between '<' and '-' : 이러는 경우 오류가 발생한다

In [3]:
# comment

In [4]:
x <- 200; x

[1] 200

In [5]:
(x = 200) # unknown function expression

[1] 200

연쇄 할당의 경우 아래와 같이 입력한다

In [6]:
x1 = x2 = x3 = 20

print(x1)
print(x2)
print(x3)

[1] 20
[1] 20
[1] 20


쌍머리 할당 연산자 '<<-'와 '->>'은 다른 기능을 가지고 있으므로 주의해야 한다

**선언된 객체의 확인**

`ls()`함수를 사용하면 현재까지 선언된 객체의 목록을 확인할 수 있다

In [7]:
ls()

[1] "x"  "x1" "x2" "x3" "y"

**선언된 객체의 삭제**

`rm()`함수를 사용하면 선언된 객체 중 원하는 객체를 삭제할 수 있다

In [8]:
rm(x1, x2) # remove x1, x2

In [9]:
ls()

[1] "x"  "x3" "y"

**생성된 객체의 저장**

`sane.image()`를 사용하면 객체를 저장할 수 있다. 확장자는 RData이다

In [10]:
save.image()

**Magic Function**

여러개의 객체를 한꺼번에 다 지우고 싶을 때에는 `?rm`을 입력하면 된다

In [11]:
?rm

또는 아래와 같은 방법을 사용하면 된다

In [12]:
rm(list = ls()) # remove all of objects

In [13]:
ls() # empty data

character(0)

#### 2. Vector, Matrix, Data Frame

##### 2.1 Vector

R에서 데이터의 최소 단위는 vector이다. vector의 크기가 1인 것을 scalar라고 한다


**기본 Sequence 만들기**

In [14]:
print(1:5) # sequence

[1] 1 2 3 4 5


`seq()`함수를 통해서도 생성이 가능하다

In [15]:
print(seq(1,5))

[1] 1 2 3 4 5


parameter `by`를 이용해 간격을 조절할 수 있다

In [16]:
print(seq(1, 5, by = 0.25))

 [1] 1.00 1.25 1.50 1.75 2.00 2.25 2.50 2.75 3.00 3.25 3.50 3.75 4.00 4.25 4.50
[16] 4.75 5.00


parameter `l`을 사용하면 갯수에 맞게 시퀀스의 길이를 조절해 준다

In [17]:
print(seq(1, 5, l = 9))

[1] 1.0 1.5 2.0 2.5 3.0 3.5 4.0 4.5 5.0


**객체의 반복**

`rep()`함수를 사용하면 객체 반복이 가능하다

In [18]:
print(rep(1:3, 2))

[1] 1 2 3 1 2 3


In [19]:
print(rep(LETTERS[1:3], 2)) # slicing

[1] "A" "B" "C" "A" "B" "C"


parameter `e`를 사용하여 문자별 반복 횟수를 지정할 수 있다

In [20]:
print(rep(1:3, e = 2)) # each

[1] 1 1 2 2 3 3


In [21]:
print(rep(LETTERS[1:3], 1:3))

[1] "A" "B" "B" "C" "C" "C"


In [22]:
print(rep(LETTERS[1:3], rep(2,3)))

[1] "A" "A" "B" "B" "C" "C"


**Vector**

`c()`함수를 사용하여 Vector를 만들 수 있다

In [23]:
print(c(1, 7, 5))

[1] 1 7 5


In [24]:
print(c('a','x','q'))

[1] "a" "x" "q"


`length()`함수를 사용하며 vector의 길이를 측정할 수 있다

In [25]:
x = c(1, 7, 5)
print(x)
print(length(x))

[1] 1 7 5
[1] 3


**Vector Arithmetic**

python에서 broadcasting과 비슷한 기능이다

In [26]:
1:3 + x

[1] 2 9 8

In [27]:
print(sqrt(x))

[1] 1.000000 2.645751 2.236068


**subsetting**

Indexing, Slicing을 하는 방법이다

In [28]:
letters[1:12] # slicing

[1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l"

In [29]:
letters[c(1, 10, 20)]

[1] "a" "j" "t"

In [30]:
(1:4)[c(T,F,T,F)] # Boolean Indexing

[1] 1 3

In [31]:
x = c(1, 5, 7, 0)
x[x > 3] # Boolean Indexing

[1] 5 7

In [32]:
x = 11:20
x[5]

[1] 15

음수 인덱싱의 경우 python과는 다르게 그 값을 제외한 vector의 모든 원소를 출력한다

In [33]:
x[-5]

[1] 11 12 13 14 16 17 18 19 20

In [34]:
x[c(3, 5)]

[1] 13 15

In [35]:
x[-c(3, 5)]

[1] 11 12 14 16 17 18 19 20

##### 2.2 Matrix

In [36]:
s = matrix(1:12, , 4)
print(s)

     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
[2,]    2    5    8   11
[3,]    3    6    9   12


비어있는 경우 차원에 맞게 자동으로 할당한다

In [37]:
p = matrix(letters[1:12], 4, 3)
print(p)

     [,1] [,2] [,3]
[1,] "a"  "e"  "i" 
[2,] "b"  "f"  "j" 
[3,] "c"  "g"  "k" 
[4,] "d"  "h"  "l" 


`class()` 함수를 사용하면 자료형을 볼 수 있다

In [38]:
class(s) # class function

[1] "matrix" "array"

`dim()` 함수는 행렬의 형태를 출력한다

In [39]:
dim(s)

[1] 3 4

`t()` 함수는 transpose(전치)를 수행하는 함수이다

In [40]:
t(s)

[,1] [,2] [,3]
[1,]  1    2    3  
[2,]  4    5    6  
[3,]  7    8    9  
[4,] 10   11   12

`nrow()` `ncol()` 함수는 각각 열과 행의 갯수를 출력한다

In [41]:
ncol(s)

[1] 4

In [42]:
nrow(s)

[1] 3

`diag()`함수는 행렬은 대각행렬을 생성한다

In [43]:
diag(3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

In [44]:
diag(1:3)

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    2    0   
[3,] 0    0    3

기존에 이미 행렬이 초기화되었을 경우 대각 원소를 추출해 출력한다

In [45]:
diag(s)

[1] 1 5 9

In [46]:
diag(p)

[1] "a" "f" "k"

`cbind()` 함수를 사용하면 column을 기준으로 vector를 합친다

In [47]:
print(cbind(c(1:4), c(11:14)))

     [,1] [,2]
[1,]    1   11
[2,]    2   12
[3,]    3   13
[4,]    4   14


`rbind()`함수를 사용하면 row를 기준으로 vector를 합친다

In [48]:
print(rbind(c(1:4), c(11:14)))

     [,1] [,2] [,3] [,4]
[1,]    1    2    3    4
[2,]   11   12   13   14


행렬 내의 모든 원소들은 같은 데이터 형태를 지녀야 한다

In [49]:
print(cbind(c(1:4), letters[1:4]))

     [,1] [,2]
[1,] "1"  "a" 
[2,] "2"  "b" 
[3,] "3"  "c" 
[4,] "4"  "d" 


##### 2.3 Data Frame

In [50]:
a = cbind(1:4, letters[1:4]) # matrix
print(a)

     [,1] [,2]
[1,] "1"  "a" 
[2,] "2"  "b" 
[3,] "3"  "c" 
[4,] "4"  "d" 


In [51]:
b = data.frame(a)
print(b)

  X1 X2
1  1  a
2  2  b
3  3  c
4  4  d


Data Frame은 column마다 각기 다른 데이터타입이 올 수 있다

In [52]:
c = data.frame(nums = 1:4, letter = letters[1:4])
c

nums letter
1 1    a     
2 2    b     
3 3    c     
4 4    d

`colnames()` `rownames()` `row.names()`를 통해 열과 행의 이름을 출력할 수 있다

In [53]:
colnames(c) # column names

[1] "nums"   "letter"

In [54]:
row.names(c) # row names

[1] "1" "2" "3" "4"

Matrix와 Data Frame을 vector로 형변환 하는 경우 아래와 같이 변환된다

In [55]:
print(c(a)) # matrix

[1] "1" "2" "3" "4" "a" "b" "c" "d"


In [56]:
print(c(b)) # data frame

$X1
[1] "1" "2" "3" "4"

$X2
[1] "a" "b" "c" "d"


In [57]:
print(c(c)) # data frame

$nums
[1] 1 2 3 4

$letter
[1] "a" "b" "c" "d"


$ 기호를 사용하여 column에 진입할 수 있다

In [58]:
print(c$letter)

[1] "a" "b" "c" "d"


**Matrix & data frame subsetting**

matrix와 data frame에 대해서 indexing, slicing을 할 수 있다

In [59]:
print(c[1]) # first column

  nums
1    1
2    2
3    3
4    4


In [60]:
print(c[1:2])

  nums letter
1    1      a
2    2      b
3    3      c
4    4      d


In [61]:
print(c[1, c(1,2)]) # row, column

  nums letter
1    1      a


In [62]:
print(c[2:4, 1]) # row, column

[1] 2 3 4
